on:
  schedule:
    - cron:  '0 11 * * *' # trigger workflow automatically at 4 am Pacific time
  workflow_dispatch: # trigger workflow manually
name: trigger build

jobs:

  build:
    name: trigger build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master # checkout master branch
      - uses: ./
        env:
          COMMIT_FILE_NAME: commit-file.txt # name of the file being created to trigger build
